// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// add_perc_cpp
DataFrame add_perc_cpp(DataFrame df, int start_col);
RcppExport SEXP _loanportr_add_perc_cpp(SEXP dfSEXP, SEXP start_colSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< int >::type start_col(start_colSEXP);
    rcpp_result_gen = Rcpp::wrap(add_perc_cpp(df, start_col));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_loanportr_add_perc_cpp", (DL_FUNC) &_loanportr_add_perc_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_loanportr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
