# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title add_perc_cpp
#' @description The c++ version of \code{\link{add_perc}} function.
#'   Adds percentage distribution columns to a summarised data frame
#' @param data A data frame that has a date or similar variable as its first
#'   column, followed by the levels of some categorical variable that makes up a
#'   total, which is the last column. Typically a data frame created by the
#'   \code{\link{vardistr_amnt}} function.
#'   @param start_col start start summing across from this column number
#'
#' @return the same data frame plus a column starting with "perc" for each of
#'   the existing variables. These added variables will add up to 100% if they
#'   are summed up row wise.
#' @export
#'
#' @examples
#' x <- add_perc_cpp(df, 2)
#'
add_perc_cpp <- function(df, start_col) {
    .Call('_loanportr_add_perc_cpp', PACKAGE = 'loanportr', df, start_col)
}

